apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alpha-somaz-applicationset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: somaz-aws-clutser
                  url: https://A1B2C3D4E5F6789012345678901234567.gr7.eu-central-1.eks.amazonaws.com # your cluster url
                  values:
                    project: somaz
                    environment: alpha
          - git:
              repoURL: git@gitlab.concrit.us:server/argocd-applicationset.git
              revision: HEAD
              directories:
                - path: values/somaz/*
                # - path: values/somaz/game  
                # - path: values/somaz/admin
  template:
    metadata:
      name: '{{values.environment}}-{{values.project}}-{{path.basename}}'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: git@gitlab.somaz.link:server/argocd-applicationset.git
        targetRevision: HEAD
        path: charts/base
        helm:
          version: v3
          releaseName: '{{values.environment}}-{{values.project}}-{{path.basename}}'
          valueFiles:
            - '../../values/{{values.project}}/{{path.basename}}/{{values.environment}}.values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{values.environment}}-{{values.project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # preserveResourcesOnDeletion: false # default is true 
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

