apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: qa-my-project-applicationset
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - cluster: example-cluster # your cluster name
                  url: https://192.168.1.17:6443  # your cluster url
                  values:
                    project: my-project
                    environment: qa1
          - git:
              repoURL: git@gitlab.example.com:example-org/helm-base-app-template.git # your source repo
              revision: HEAD
              directories:
                # - path: values/my-project/*
                - path: values/my-project/game
                - path: values/my-project/admin
                - path: values/my-project/app-admin
  template:
    metadata:
      name: '{{values.environment}}-{{values.project}}-{{path.basename}}'
      labels:
        environment: '{{values.environment}}'
        project: '{{values.project}}'
        app-name: '{{path.basename}}'
    spec:
      project: '{{values.project}}'
      source:
        repoURL: git@gitlab.example.com:example-org/helm-base-app-template.git
        targetRevision: HEAD
        path: charts/base
        helm:
          version: v3
          releaseName: '{{values.environment}}-{{values.project}}-{{path.basename}}'
          valueFiles:
            - '../../values/{{values.project}}/{{path.basename}}/{{values.environment}}.values.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{values.environment}}-{{values.project}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        # preserveResourcesOnDeletion: false # default is true 
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true



